version: '3'

networks:
  ChessNet:
    driver: bridge


services:

  db:
    image: postgres
    restart: always
    container_name: ChessDb
    environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: test
    ports:
        - '4002:5432'

    volumes:
        - ./data:/var/lib/postgresql/data

    networks:
        - ChessNet


  server:
    container_name: ChessServer
    build:
        context: .
        dockerfile: Server/Dockerfile
    ports:
        - '4001:80'

    networks:
        - ChessNet

    depends_on:
        - db
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s


    environment:
        ASPNETCORE_ENVIRONMENT: Production

volumes:
  db:
    driver: local    