name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: logging in to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx build . --file ./Server/Dockerfile --tag 112axel/blazor-chess:latest --platform linux/amd64,linux/arm64 --push

        
